apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo
  labels:
    app: mongo

spec:
  serviceName: mongo
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - name: mongo
          image: mongo:6.0
          imagePullPolicy: Never
          ports:
            - containerPort: 27017
              name: mongo
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: mongo-config
                  key: mongo_user
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: mongo_password
            - name: MONGO_INITDB_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: mongo-config
                  key: Mongo_DB
          volumeMounts: # to mount volumes inside container
            - name: mongo-data # reference to volumeClaimTemplates
              mountPath: /data/db
            - name: mongo-init 
              mountPath: /docker-entrypoint-initdb.d
              readOnly: true
      volumes:
        - name: mongo-init # to mount local init scripts At start onlyyyy
          hostPath: 
            path: /mnt/d/pro-shop/mongo-init # change to your local path of mongo-init
            type: DirectoryOrCreate # create if not exists
  volumeClaimTemplates: # to create persistent volume for mongo data
    - metadata:
        name: mongo-data # referenced in volumeMounts
      spec:
        accessModes: ["ReadWriteOnce"] # can be mounted as read-write by a single node
        resources:
          requests:
            storage: 1Gi